<a href="https://colab.research.google.com/github/alishadaudi/DDSA-data-science-projects/blob/main/TX_Schools_Pycaret.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Code snippet 1
# Installing pycaret for ML modeling
!pip install git+https://github.com/pycaret/pycaret.git

In [ ]:
# Code snippet 2
# Importing regression components from pycaret
from pycaret.regression import *

In [ ]:
# Code snippet 3
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/2023%20Texas%20High%20Schools%20Scores.csv')

# Display the data
data

,School,School URL,District,District URL,City,City URL,Zip,County,Phone,Is Title I,...,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,Standard Score
0,Lasa High School,https://www.schooldigger.com/go/TX/schools/089...,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78724,Travis County,(512) 414-2589,No,...,16.5,14.0,2.6,0.1,23.2,23.6,0.1,6.9,43.6,97.2
1,School For The Talented And Gifted,https://www.schooldigger.com/go/TX/schools/162...,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16...,Dallas,https://www.schooldigger.com/go/TX/city/Dallas...,75203,Dallas County,(972) 925-5970,Yes,...,17.5,32.5,8.8,0.4,15.5,41.2,0.2,2.8,31.0,96.9
2,School Of Science And Engineering,https://www.schooldigger.com/go/TX/schools/162...,Dallas Independent School District,https://www.schooldigger.com/go/TX/district/16...,Dallas,https://www.schooldigger.com/go/TX/city/Dallas...,75203,Dallas County,(972) 925-5960,Yes,...,19.7,54.0,9.9,0.2,12.5,61.6,0.6,1.0,14.2,96.6
3,Health Careers High School,https://www.schooldigger.com/go/TX/schools/331...,Northside Independent School District,https://www.schooldigger.com/go/TX/district/33...,San Antonio,https://www.schooldigger.com/go/TX/city/San+An...,78229,Bexar County,(210) 397-5400,No,...,17.8,22.2,5.2,0.1,19.3,54.4,0.3,3.1,17.6,95.5
4,Debakey H S For Health Prof,https://www.schooldigger.com/go/TX/schools/236...,Houston Independent School District,https://www.schooldigger.com/go/TX/district/23...,Houston,https://www.schooldigger.com/go/TX/city/Housto...,77030,Harris County,(713) 741-2410,Yes,...,18.4,42.9,16.8,0.5,30.0,37.1,0.4,2.0,13.1,95.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,W B Bizzell Academy,https://www.schooldigger.com/go/TX/schools/321...,Navasota Independent School District,https://www.schooldigger.com/go/TX/district/32...,Navasota,https://www.schooldigger.com/go/TX/city/Navaso...,77868,Grimes County,(936) 825-4296,No,...,9.0,83.3,30.0,0.0,0.0,36.7,0.0,3.3,30.0,1.7
1817,Phoenix High School,https://www.schooldigger.com/go/TX/schools/183...,Elgin Independent School District,https://www.schooldigger.com/go/TX/district/18...,Elgin,https://www.schooldigger.com/go/TX/city/Elgin/...,78621,Bastrop County,(512) 281-9774,No,...,9.3,77.1,16.7,0.0,0.0,66.7,0.0,0.0,16.7,1.5
1818,Graduation Prep Academy Navarro,https://www.schooldigger.com/go/TX/schools/089...,Austin Independent School District,https://www.schooldigger.com/go/TX/district/08...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78758,Travis County,(512) 414-2896,No,...,22.7,93.4,12.1,0.0,3.3,80.2,0.0,2.2,2.2,1.3
1819,Munday,https://www.schooldigger.com/go/TX/schools/000...,University Of Texas University Charter School,https://www.schooldigger.com/go/TX/district/00...,Austin,https://www.schooldigger.com/go/TX/city/Austin...,78723,Travis County,(512) 997-8872,No,...,4.6,78.6,21.4,0.0,0.0,42.9,0.0,7.1,28.6,1.0
1820,La Feria Academy,https://www.schooldigger.com/go/TX/schools/260...,La Feria Independent School District,https://www.schooldigger.com/go/TX/district/26...,La Feria,https://www.schooldigger.com/go/TX/city/La+Fer...,78559,Cameron County,(956) 797-8360,Yes,...,8.2,90.9,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.3

In [ ]:
# Code snippet 4
# Displaying dataset columns
data.columns

Index(['School', 'School URL', 'District', 'District URL', 'City', 'City URL',
       'Zip', 'County', 'Phone', 'Is Title I', 'Is Charter', 'Is Magnet',
       'Is Virtual', 'Number Students', 'Number Full-time Teachers',
       'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
       'Percent Homes Rented', 'Percent of Unemployment',
       'Percent Parents with Masters and above education',
       'Percent parents with less than High School education',
       'Percent Home Incomes with less than Median income',
       'Home Prices Ranking', 'Community Health Ranking', 'Standard Score'],
      dtype='object')

In [ ]:
# Code snippet 5
# Setting the target variable
y = 'Standard Score'

In [ ]:
# Code snippet 6
# Setting the ignored columns list
ignored_cols = ['School', 'School URL', 'District URL', 'City URL',  'Phone',
                'Home Prices Ranking', 'Community Health Ranking']

In [ ]:
# Code snippet 7
# Setting the categorical columns list
cat_cols = ['District', 'City', 'Zip', 'County', 'Is Title I', 'Is Charter', 'Is Magnet',
      'Is Virtual']

In [ ]:
# Code snippet 8
# Setting the numerical columns list
num_cols  = ['Number Students', 'Number Full-time Teachers',
      'Student/Teacher Ratio', 'Percent Free/Disc Lunch',
      'Percent Homes Rented', 'Percent of Unemployment',
      'Percent Parents with Masters and above education',
      'Percent parents with less than High School education',
      'Percent Home Incomes with less than Median income']

In [ ]:
# Code snippet 9
# Setting/configuring ML setup with pycaret
regression_setup = setup(data,
                        target = y,
                        ignore_features = ignored_cols,
                        categorical_features = cat_cols,
                        numeric_features = num_cols)

In [ ]:
# Code snippet 10
# Invoking ML algorithms
compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

HuberRegressor()

In [ ]:
# Code snippet 11
# Performing cross validation (running the best algorithm 10 times)
best_model = create_model('huber')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
# Code snippet 12
# Importing the client dataset(for which the target values/std score needs to be predicted)
client_data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/TX%20High%20Schools%20-%20Client%20Data.csv')


client_data

,School,District,City,Zip,County,Phone,Is Title I,Is Charter,Is Magnet,Is Virtual,...,Number Full-time Teachers,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking
0,Texas High School 1,Fort Bend Independent School District,Sugar Land,77498,Fort Bend,(281) 634-2000,No,Yes,No,Yes,...,77.0,9.0,0.12,0.09,0.36,0.99,0.46,0.29,0.84,0.66
1,Texas High School 2,Nazareth Independent School District,Nazareth,79063,Castro,(806) 945-2231,No,No,No,Yes,...,82.0,16.0,0.71,0.25,0.55,0.04,0.21,0.74,0.99,0.77
2,Texas High School 3,Treetops School International,Euless,76040,Tarrant,(817) 283-1771,No,No,No,Yes,...,122.0,10.0,0.09,0.96,0.44,0.17,0.45,0.99,0.34,0.27
3,Texas High School 4,Boerne Independent School District,Boerne,78006,Kendall,(830) 357-2600,No,No,No,No,...,86.0,15.0,0.72,0.69,0.10,0.60,0.53,0.45,0.42,0.33
4,Texas High School 5,Barbers Hill Independent School District,Mont Belvieu,77580,Chambers,(281) 576-2221,(n/a),No,No,Yes,...,93.0,10.0,0.28,0.57,0.01,0.10,0.17,0.32,0.23,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,Texas High School 213,McGregor Independent School District,Mc Gregor,76657,McLennan,(254) 840-2853,No,No,No,Yes,...,38.0,11.0,0.71,0.12,0.01,0.01,0.42,0.00,0.01,0.01
213,Texas High School 214,Dallas Independent School District,Dallas,75214,Dallas,(972) 502-4400,No,No,No,Yes,...,100.0,16.9,0.60,0.09,0.00,0.01,0.66,0.00,0.01,0.01
214,Texas High School 215,Sanger Independent School District,Sanger,76266,Denton,(940) 458-7497,Yes,No,No,No,...,52.0,15.3,0.36,0.03,0.01,0.01,0.25,0.00,0.02,0.02
215,Texas High School 216,Neches Independent School District,Palestine,75803,Anderson,(903) 584-3443,No,No,No,No,...,12.0,9.5,0.42,0.07,0.00,0.01,0.09,0.00,0.03,0.02
216,Texas High School 217,Savoy Independent School District,Savoy,75479,Fannin,(903) 965-4024,No,No,No,No,...,14.0,9.7,0.48,0.01,0.02,0.01,0.05,0.00,0.07,0.05

In [ ]:
# Code snippet 13
# Predicting standard scores for the client dataset
predictions = predict_model(best_model, client_data)

# Exporting predictions to a CSV file
predictions.to_csv('TX Std Scores predictions.csv')

In [ ]:
predictions

,School,District,City,Zip,County,Phone,Is Title I,Is Charter,Is Magnet,Is Virtual,...,Student/Teacher Ratio,Percent Free/Disc Lunch,Percent Homes Rented,Percent of Unemployment,Percent Parents with Masters and above education,Percent parents with less than High School education,Percent Home Incomes with less than Median income,Home Prices Ranking,Community Health Ranking,prediction_label
0,Texas High School 1,Fort Bend Independent School District,Sugar Land,77498,Fort Bend,(281) 634-2000,No,Yes,No,Yes,...,9.0,0.12,0.09,0.36,0.99,0.46,0.29,0.84,0.66,114.642356
1,Texas High School 2,Nazareth Independent School District,Nazareth,79063,Castro,(806) 945-2231,No,No,No,Yes,...,16.0,0.71,0.25,0.55,0.04,0.21,0.74,0.99,0.77,105.530052
2,Texas High School 3,Treetops School International,Euless,76040,Tarrant,(817) 283-1771,No,No,No,Yes,...,10.0,0.09,0.96,0.44,0.17,0.45,0.99,0.34,0.27,87.379909
3,Texas High School 4,Boerne Independent School District,Boerne,78006,Kendall,(830) 357-2600,No,No,No,No,...,15.0,0.72,0.69,0.10,0.60,0.53,0.45,0.42,0.33,106.180556
4,Texas High School 5,Barbers Hill Independent School District,Mont Belvieu,77580,Chambers,(281) 576-2221,(n/a),No,No,Yes,...,10.0,0.28,0.57,0.01,0.10,0.17,0.32,0.23,0.18,114.838642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,Texas High School 213,McGregor Independent School District,Mc Gregor,76657,McLennan,(254) 840-2853,No,No,No,Yes,...,11.0,0.71,0.12,0.01,0.01,0.42,0.00,0.01,0.01,96.260024
213,Texas High School 214,Dallas Independent School District,Dallas,75214,Dallas,(972) 502-4400,No,No,No,Yes,...,16.9,0.60,0.09,0.00,0.01,0.66,0.00,0.01,0.01,81.950887
214,Texas High School 215,Sanger Independent School District,Sanger,76266,Denton,(940) 458-7497,Yes,No,No,No,...,15.3,0.36,0.03,0.01,0.01,0.25,0.00,0.02,0.02,104.005379
215,Texas High School 216,Neches Independent School District,Palestine,75803,Anderson,(903) 584-3443,No,No,No,No,...,9.5,0.42,0.07,0.00,0.01,0.09,0.00,0.03,0.02,108.097678
216,Texas High School 217,Savoy Independent School District,Savoy,75479,Fannin,(903) 965-4024,No,No,No,No,...,9.7,0.48,0.01,0.02,0.01,0.05,0.00,0.07,0.05,124.770409